[package]
name = "viewstamped-replication"
description = "A Rust-based implementation of the Viewstamped Replication consensus protocol."
version = "0.3.0"
authors = ["Miguel D. Salcedo <miguel@salcedo.cc>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/misalcedo/vr"
repository = "https://github.com/misalcedo/vr"
documentation = "https://docs.rs/viewstamped-replication"

[profile.release]
lto = true
debug = true

[features]
default = []

[dependencies]
uuid = { version = "1.7.0", features = ["v7" ] }
