name: Linters

on: [ push, workflow_dispatch ]

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.7.3
      - name: Lint
        run: cargo clippy --all-features
      - name: Format
        run: cargo fmt
